#!/usr/bin/env python3
"""
Agent Teams Session Report Generator
Reads team-session-log.jsonl and produces formatted reports.

Usage:
  python observability/report-generator.py
  python observability/report-generator.py --input team-session-log.jsonl
  python observability/report-generator.py --format html -o report.html
  python observability/report-generator.py --format json
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path


def load_events(path):
    events = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    events.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return events


def analyze(events):
    teammates = Counter(e.get("teammate", "unknown") for e in events)
    statuses = Counter(e.get("status", "unknown") for e in events)
    timestamps = sorted(e.get("timestamp", "") for e in events)

    return {
        "total_events": len(events),
        "teammates": dict(teammates.most_common()),
        "teammate_count": len(teammates),
        "statuses": dict(statuses.most_common()),
        "completed": statuses.get("completed", 0),
        "blocked": statuses.get("blocked", 0),
        "first_event": timestamps[0] if timestamps else None,
        "last_event": timestamps[-1] if timestamps else None,
        "events": events,
    }


def format_markdown(stats):
    lines = [
        "# Agent Teams Session Report",
        "",
        f"**Duration:** {stats['first_event']} → {stats['last_event']}",
        f"**Teammates:** {stats['teammate_count']}",
        f"**Total tasks:** {stats['total_events']}",
        f"**Completed:** {stats['completed']} | **Blocked:** {stats['blocked']}",
        "",
        "---",
        "",
        "## Team Overview",
        "",
        "| Teammate | Tasks | % of Total |",
        "|----------|-------|------------|",
    ]

    total = stats["total_events"] or 1
    for name, count in stats["teammates"].items():
        pct = round(count / total * 100)
        lines.append(f"| {name} | {count} | {pct}% |")

    lines += [
        "",
        "## Task Timeline",
        "",
        "| # | Time | Teammate | Task | Status |",
        "|---|------|----------|------|--------|",
    ]

    for i, e in enumerate(stats["events"], 1):
        ts = e.get("timestamp", "—")
        tm = e.get("teammate", "—")
        task = e.get("task", "—")[:80]
        st = e.get("status", "—")
        lines.append(f"| {i} | {ts} | {tm} | {task} | {st} |")

    lines += [
        "",
        "## Status Distribution",
        "",
    ]
    for status, count in stats["statuses"].items():
        bar = "#" * min(count * 3, 40)
        lines.append(f"  {status:<12} {bar} ({count})")

    lines += ["", "---", "*Generated by Agent Teams Report Generator*"]
    return "\n".join(lines)


def format_json(stats):
    return json.dumps(stats, indent=2, default=str)


def format_html(stats):
    rows = ""
    for e in stats["events"]:
        ts = e.get("timestamp", "—")
        tm = e.get("teammate", "—")
        task = e.get("task", "—")[:80]
        st = e.get("status", "—")
        color = "#51cf66" if st == "completed" else "#fcc419" if st == "blocked" else "#94a3b8"
        rows += f"<tr><td>{ts}</td><td>{tm}</td><td>{task}</td><td style='color:{color};font-weight:700'>{st}</td></tr>\n"

    teammate_rows = ""
    total = stats["total_events"] or 1
    for name, count in stats["teammates"].items():
        pct = round(count / total * 100)
        teammate_rows += f"<tr><td>{name}</td><td>{count}</td><td>{pct}%</td></tr>\n"

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Agent Teams Session Report</title>
<style>
*{{box-sizing:border-box}}
body{{font-family:'Inter',system-ui,sans-serif;background:#0f172a;color:#e2e8f0;max-width:900px;margin:0 auto;padding:40px 20px}}
h1{{color:#f8fafc;text-align:center}} h2{{color:#94a3b8}}
.stat{{display:inline-block;background:#1e293b;border-radius:8px;padding:16px 24px;margin:8px;text-align:center}}
.stat-value{{font-size:2rem;font-weight:800;color:#51cf66}}
.stat-label{{font-size:0.8rem;color:#64748b;text-transform:uppercase}}
table{{width:100%;border-collapse:collapse;margin:16px 0;background:#1e293b;border-radius:8px;overflow:hidden}}
th{{text-align:left;color:#64748b;padding:10px 12px;border-bottom:2px solid #0f172a;font-size:0.8rem;text-transform:uppercase}}
td{{padding:10px 12px;border-bottom:1px solid #0f172a55;font-size:0.85rem}}
</style></head><body>
<h1>Agent Teams Session Report</h1>
<div style="text-align:center">
<div class="stat"><div class="stat-value">{stats['teammate_count']}</div><div class="stat-label">Teammates</div></div>
<div class="stat"><div class="stat-value">{stats['total_events']}</div><div class="stat-label">Tasks</div></div>
<div class="stat"><div class="stat-value">{stats['completed']}</div><div class="stat-label">Completed</div></div>
<div class="stat"><div class="stat-value">{stats['blocked']}</div><div class="stat-label">Blocked</div></div>
</div>
<h2>Team Overview</h2>
<table><tr><th>Teammate</th><th>Tasks</th><th>Share</th></tr>{teammate_rows}</table>
<h2>Task Timeline</h2>
<table><tr><th>Time</th><th>Teammate</th><th>Task</th><th>Status</th></tr>{rows}</table>
<div style="text-align:center;color:#475569;font-size:0.8rem;margin-top:40px">Generated by Agent Teams Report Generator</div>
</body></html>"""


def main():
    parser = argparse.ArgumentParser(description="Agent Teams Session Report Generator")
    parser.add_argument("--input", "-i", default="team-session-log.jsonl", help="Input log file")
    parser.add_argument("--format", "-f", choices=["md", "json", "html"], default="md", help="Output format")
    parser.add_argument("--output", "-o", help="Output file (default: stdout)")
    args = parser.parse_args()

    log_path = Path(args.input)
    if not log_path.exists():
        print(f"No log file found at {log_path}")
        print()
        print("To enable session logging:")
        print("1. Add hooks/capture-output.sh to your settings.json hooks")
        print("2. Run an Agent Teams session")
        print("3. Run this script to generate a report")
        print()
        print("See hooks/capture-output.sh for setup instructions.")
        sys.exit(1)

    events = load_events(log_path)
    if not events:
        print("Log file is empty.")
        sys.exit(1)

    stats = analyze(events)

    formatters = {"md": format_markdown, "json": format_json, "html": format_html}
    output = formatters[args.format](stats)

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)
        print(f"Report saved to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
