#!/bin/bash
# Generate a summary report from team-session-log.jsonl
#
# Run this after a team session ends to see what happened:
#   ./hooks/session-summary.sh
#   ./hooks/session-summary.sh --input custom-log.jsonl
#
# Output: TEAM_SESSION_SUMMARY.md

LOG_FILE="${1:-team-session-log.jsonl}"
OUTPUT="TEAM_SESSION_SUMMARY.md"

if [ ! -f "$LOG_FILE" ]; then
    echo "No session log found at $LOG_FILE"
    echo "Enable logging by adding capture-output.sh to your hooks."
    echo "See hooks/capture-output.sh for setup instructions."
    exit 1
fi

python3 << 'PYTHON'
import json
import sys
from collections import Counter
from datetime import datetime

log_file = sys.argv[1] if len(sys.argv) > 1 else "team-session-log.jsonl"
output_file = "TEAM_SESSION_SUMMARY.md"

events = []
with open(log_file) as f:
    for line in f:
        line = line.strip()
        if line:
            try:
                events.append(json.loads(line))
            except json.JSONDecodeError:
                continue

if not events:
    print("No events found in log.")
    sys.exit(1)

# Analyze
teammates = Counter(e.get("teammate", "unknown") for e in events)
statuses = Counter(e.get("status", "unknown") for e in events)
timestamps = [e.get("timestamp", "") for e in events]
timestamps.sort()

first = timestamps[0] if timestamps else "—"
last = timestamps[-1] if timestamps else "—"

# Generate report
lines = [
    "# Team Session Summary",
    "",
    f"**Session:** {first} → {last}",
    f"**Total events:** {len(events)}",
    f"**Teammates active:** {len(teammates)}",
    "",
    "---",
    "",
    "## Teammates",
    "",
    "| Teammate | Tasks Completed |",
    "|----------|----------------|",
]

for name, count in teammates.most_common():
    lines.append(f"| {name} | {count} |")

lines += [
    "",
    "## Task Status",
    "",
    "| Status | Count |",
    "|--------|-------|",
]

for status, count in statuses.most_common():
    lines.append(f"| {status} | {count} |")

lines += [
    "",
    "## Timeline",
    "",
    "| Time | Teammate | Task | Status |",
    "|------|----------|------|--------|",
]

for e in events:
    ts = e.get("timestamp", "—")
    tm = e.get("teammate", "—")
    task = e.get("task", "—")[:60]
    st = e.get("status", "—")
    lines.append(f"| {ts} | {tm} | {task} | {st} |")

lines += ["", "---", "", "*Generated by session-summary.sh*"]

with open(output_file, "w") as f:
    f.write("\n".join(lines))

print(f"Summary written to {output_file}")
print(f"  Teammates: {len(teammates)}")
print(f"  Events: {len(events)}")
print(f"  Completed: {statuses.get('completed', 0)}")
PYTHON

exit $?
